app = "rebalancor-arbitrum-ethrise"

kill_signal = "SIGTERM"
kill_timeout = 5
processes = []

[env]
  VAULT_CONTRACT="0xf7EDB240DbF7BBED7D321776AFe87D1FBcFD0A94"
  LEVERAGED_TOKEN_CONTRACT="0x46D06cf8052eA6FdbF71736AF33eD23686eA1452"
  MIN_LEVERAGE_RATIO_IN_ETHER=1700000000000000000
  MAX_LEVERAGE_RATIO_IN_ETHER=2500000000000000000
  SENTRY_APP_NAME="rebalancor-arbitrum-ethrise"
