# fly.toml file generated for arbitrage-kovan-weth-usdc on 2021-11-04T12:32:51+07:00

app = "kovan-rebalance-ethrise"

kill_signal = "SIGTERM"
kill_timeout = 5
processes = []

[env]
  VAULT_CONTRACT="0x42B6BAE111D9300E19F266Abf58cA215f714432c"
  LEVERAGED_TOKEN_CONTRACT="0xc4676f88663360155c2bc6d2A482E34121a50b3b"
  MIN_LEVERAGE_RATIO_IN_ETHER=1700000000000000000
  MAX_LEVERAGE_RATIO_IN_ETHER=2500000000000000000
  SENTRY_APP_NAME="kovan-rebalance-ethrise"
